/**
 * 麻雀戦績管理システムのデータモデル型定義
 * Data model type definitions for Mahjong Score Management System
 */

import { Timestamp } from 'firebase/firestore';

/**
 * ウマ設定
 * Uma (rank bonus) settings
 */
export interface UmaSettings {
  /** トップ-ビリ間のウマ (Top-Bottom uma difference) */
  topBottom: number;
  /** 2-3位間のウマ (2nd-3rd place uma difference) */
  middlePair: number;
}

/**
 * オカ設定
 * Oka (starting point adjustment) settings
 */
export interface OkaSettings {
  /** 開始点 (Starting points) */
  startPoints: number;
  /** 返し点 (Return points for calculation) */
  returnPoints: number;
}

/**
 * ヤキトリ設定
 * Yakitori (penalty for never placing 1st) settings
 */
export interface YakitoriSettings {
  /** ヤキトリ有効/無効 (Yakitori enabled/disabled) */
  enabled: boolean;
  /** ペナルティスコア (Penalty score) */
  penalty: number;
}

/**
 * チップ設定
 * Chip settings
 */
export interface ChipSettings {
  /** チップ有効/無効 (Chip enabled/disabled) */
  enabled: boolean;
  /** 初期チップ枚数 (Initial chip count) */
  initialCount: number;
  /** 1枚あたりのスコア (Points per chip) */
  pointsPerChip: number;
}

/**
 * 部屋設定
 * Room settings
 */
export interface RoomSettings {
  /** ウマ設定 (Uma settings) */
  uma: UmaSettings;
  /** オカ設定 (Oka settings) */
  oka: OkaSettings;
  /** ヤキトリ設定 (Yakitori settings) */
  yakitori: YakitoriSettings;
  /** チップ設定 (Chip settings) */
  chip: ChipSettings;
}

/**
 * 部屋
 * Room - A container for members and game records
 */
export interface Room {
  /** 部屋ID (Firestore自動生成) (Room ID - auto-generated by Firestore) */
  id: string;
  /** 部屋名 (作成日時: YYYYMMDDHHmm形式) (Room name - creation datetime in YYYYMMDDHHmm format) */
  name: string;
  /** 作成日時 (Creation timestamp) */
  createdAt: Timestamp;
  /** 部屋設定 (Room settings) */
  settings: RoomSettings;
  /** 現在の半荘ID (Current game ID - null if no active game) */
  currentGameId: string | null;
  /** 清算済みフラグ (Settlement flag) */
  isSettled: boolean;
  /** 清算日時 (Settlement timestamp - null if not settled) */
  settledAt: Timestamp | null;
}

/**
 * メンバー
 * Member - A player in a room
 */
export interface Member {
  /** メンバーID (部屋ごとに一意) (Member ID - unique per room) */
  id: string;
  /** ユーザーID (Cookie保存、複数部屋で共通) (User ID - stored in cookie, shared across rooms) */
  userId: string;
  /** 所属部屋ID (Room ID this member belongs to) */
  roomId: string;
  /** 表示名 (部屋ごとに設定可能) (Display name - can be set per room) */
  name: string;
  /** 参加日時 (Join timestamp) */
  joinedAt: Timestamp;
}

/**
 * 半荘結果
 * Game result for a single player in a game
 */
export interface GameResult {
  /** メンバーID (Member ID) */
  memberId: string;
  /** メンバー名 (スナップショット) (Member name - snapshot at game time) */
  memberName: string;
  /** 素点 (Raw score at end of game) */
  rawScore: number;
  /** 順位 (1-4) (Rank - 1st to 4th place) */
  rank: number;
  /** ウマ (Uma bonus based on rank) */
  uma: number;
  /** オカ (Oka adjustment) */
  oka: number;
  /** チップ増減 (+/-) (Chip count change) */
  chipCount: number;
  /** チップスコア (Chip score contribution) */
  chipScore: number;
  /** 最終スコア（チップ除く） (Final score excluding chips) */
  finalScore: number;
  /** 最終スコア（チップ含む） (Final score including chips) */
  finalScoreWithChip: number;
}

/**
 * 半荘
 * Game - A single hanchan (half-game) record
 */
export interface Game {
  /** 半荘ID (Firestore自動生成) (Game ID - auto-generated by Firestore) */
  id: string;
  /** 部屋ID (Room ID) */
  roomId: string;
  /** N回目 (Game number - Nth game in the room) */
  gameNumber: number;
  /** 実施日時 (Played timestamp) */
  playedAt: Timestamp;
  /** プレイヤー数 (3人または4人) (Player count - 3 or 4) */
  playerCount: 3 | 4;
  /** 各プレイヤーの結果 (Results for each player) */
  results: GameResult[];
}

/**
 * メンバースコア（集計用）
 * Member score - Aggregated statistics for a member
 */
export interface MemberScore {
  /** メンバーID (Member ID) */
  memberId: string;
  /** メンバー名 (Member name) */
  memberName: string;
  /** 累計スコア (Total accumulated score) */
  totalScore: number;
  /** 参加半荘数 (Number of games played) */
  gamesPlayed: number;
  /** 順位別回数 (Count by rank) */
  ranks: {
    /** 1位回数 (First place count) */
    first: number;
    /** 2位回数 (Second place count) */
    second: number;
    /** 3位回数 (Third place count) */
    third: number;
    /** 4位回数 (Fourth place count) */
    fourth: number;
  };
}

/**
 * スコア計算結果
 * Score calculation result
 */
export interface ScoreCalculation {
  /** オカ (Oka adjustment) */
  oka: number;
  /** ウマ (Uma bonus) */
  uma: number;
  /** 最終スコア（チップ除く） (Final score excluding chips) */
  finalScore: number;
}
